name:                parliamentaryGazette
version:             0.1.0.0
github:              "githubuser/parliamentaryGazette"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/parliamentaryGazette#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.2.2
- lens >= 4.16.1
- aeson >= 1.2.4.0
- bytestring >= 0.10.8.2
- mtl >= 2.2.2
- transformers >=0.5.2.0
- aeson-pretty >= 0.8.5


library:
  source-dirs: src

executables:
  parliamentaryGazette-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parliamentaryGazette

tests:
  parliamentaryGazette-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parliamentaryGazette
